// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAs2zlOsy28ttLRrru7D1yTz7pE-1SyKU',
    appId: '1:532440630758:web:71eb6bf3a0a93da5a0c227',
    messagingSenderId: '532440630758',
    projectId: 'pithi-potha',
    authDomain: 'pithi-potha.firebaseapp.com',
    storageBucket: 'pithi-potha.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtFe44hnpBtNOJV--f7Z8McK0haJNUOJE',
    appId: '1:532440630758:android:8e80296c7e144694a0c227',
    messagingSenderId: '532440630758',
    projectId: 'pithi-potha',
    storageBucket: 'pithi-potha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCALhDHcwLjs9rYQxu8rCcMRjeogA5JVdE',
    appId: '1:532440630758:ios:86fa5a681ca34556a0c227',
    messagingSenderId: '532440630758',
    projectId: 'pithi-potha',
    storageBucket: 'pithi-potha.firebasestorage.app',
    iosBundleId: 'com.pirith.pitithpotha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAs2zlOsy28ttLRrru7D1yTz7pE-1SyKU',
    appId: '1:532440630758:web:e2dfaa5b0cf5ad9ba0c227',
    messagingSenderId: '532440630758',
    projectId: 'pithi-potha',
    authDomain: 'pithi-potha.firebaseapp.com',
    storageBucket: 'pithi-potha.firebasestorage.app',
  );
}
